services:
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=/api
      - NEXT_PUBLIC_AI_URL=/ai
    networks:
      - internal
    depends_on:
      - backend
      - aiserver
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_URL=db:5432/behindy
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_PASSWORD=${REDIS_PASSWORD}
      
      - JWT_SECRET=${JWT_SECRET}
      - FIELD_KEY=${FIELD_KEY}
      - TABLE_KEY=${TABLE_KEY}
      
      - SEOUL_METRO_API_KEY=${SEOUL_METRO_API_KEY:-TEMP_KEY}
      - SEOUL_METRO_API_BASE_URL=http://swopenapi.seoul.go.kr/api/subway
      - SEOUL_METRO_API_ENABLED=${METRO_API_ENABLED}
      - SEOUL_METRO_API_TIMEOUT=10000
      - SEOUL_METRO_API_RETRY_COUNT=3
      - SEOUL_METRO_API_ENABLED_LINES=${METRO_ENABLED_LINES}
      - SEOUL_METRO_CACHE_TTL=180
      - SEOUL_METRO_API_UPDATE_INTERVAL=${METRO_UPDATE_INTERVAL}
      - SEOUL_METRO_MONITORING_DAILY_LIMIT=${METRO_DAILY_LIMIT}
    networks:
      - internal
    depends_on:
      - db
      - redis
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  aiserver:
    build: ./aiserver
    container_name: aiserver
    restart: always
    expose:
      - 8000
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        max-size: "10m"    # 로그 파일 최대 크기
        max-file: "3"      # 보관할 로그 파일 수

  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - internal

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - internal

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
    depends_on:
      - frontend
    networks:
      - internal

volumes:
  db-data:

networks:
  internal:
    driver: bridge