# Production 환경 전용 로깅 설정
logging:
  level:
    # 백엔드 기본 레벨: INFO
    com.example.backend: INFO

    # 필터: WARN 이상만 (DB 저장으로 충분)
    com.example.backend.filter: WARN
    com.example.backend.security.jwt: WARN

    # 서비스: INFO
    com.example.backend.service: INFO

    # 스케줄러: WARN (성공은 로그 없음, 실패만 기록)
    com.example.backend.service.MetroDataScheduler: WARN
    com.example.backend.service.AIStoryScheduler: WARN

    # 외부 라이브러리: 최소화
    org.springframework.web.client.RestTemplate: INFO
    org.apache.http: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
